name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: gcc:13

    steps:
      - name: Checkout game
        uses: actions/checkout@v2

      - name: Setup SDL2 dependencies
        run: |
          apt-get update
          apt-get install -y build-essential libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

      - name: Build project
        run: |
          make clean
          make

      - name: Running
        run: |
          make run
